### ISSUE TITLE
https://pastebin.com/9cgPkM6m

### ISSUE THREAD

**Issue by royhodge** [irinatag/cassim-marketplace#2]
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"cassim_development", "username"=>"jurnal", "password"=>nil, "host"=>"localhost", "port"=>5432}
FATAL:  role "root" does not exist

^ is my result when attempting to run rake db:drop db:create db:migrate rake etsy:scrape as per README.md .. thanks for any help resolving this! 

root@ubuntu-s-1vcpu-1gb-nyc1-01:~/cassim-marketplace# bin/rake db:drop db:create db:migrate rake etsy:scrape

**Comment by royhodge** [comment]
Resolved. Note to self: Never run as root! #forthelulz

**Comment by irinatag** [comment]
@royhodge great! :)
